### ISSUE TITLE
XenoLib not working

### ISSUE THREAD

**Issue by o0SoloWolf0o** [PredatorCZ/XenoLib#11]
Plugin could not be compiled

TypeError: Cannot read property 'NOOP_NULL' of undefined
    at eval (betterdiscord://plugins/1XenoLib.plugin.js:1414:33)
    at buildPlugin (betterdiscord://plugins/1XenoLib.plugin.js:1416:7)
    at eval (betterdiscord://plugins/1XenoLib.plugin.js:2692:7)
    at eval (betterdiscord://plugins/1XenoLib.plugin.js:2693:3)
    at Object.requireAddon (<anonymous>:4:43438)
    at Object.loadAddon (<anonymous>:4:9197)
    at Object.loadAddon (<anonymous>:4:41165)
    at AsyncFunction.<anonymous> (<anonymous>:4:7353)

**Comment by Hornetsaysshaw** [comment]
#3 
You've got the wrong github
