### ISSUE TITLE
Please fix the compile error due to Disocrd's revamp in October

### ISSUE THREAD

**Issue by ghost** [PredatorCZ/XenoLib#13]
`TypeError: Cannot read property 'NOOP_NULL' of undefined
    at eval (betterdiscord://plugins/1XenoLib.plugin.js:1414:33)
    at buildPlugin (betterdiscord://plugins/1XenoLib.plugin.js:1416:7)
    at eval (betterdiscord://plugins/1XenoLib.plugin.js:2692:7)
    at eval (betterdiscord://plugins/1XenoLib.plugin.js:2693:3)
    at Object.requireAddon (<anonymous>:4:39192)
    at Object.loadAddon (<anonymous>:4:9163)
    at Object.loadAddon (<anonymous>:4:36864)
    at AsyncFunction.<anonymous> (<anonymous>:4:7155)`

**Comment by brwcat** [comment]
BetterDiscord still has a compilation error with XenoLib. It's now a broken dependency for a lot of plugins.
![image](https://user-images.githubusercontent.com/66891620/216165455-1e76878f-4ec5-4272-a806-71117474b5b5.png)

**Comment by ghost** [comment]
> BetterDiscord still has a compilation error with XenoLib. It's now a broken dependency for a lot of plugins. ![image](https://user-images.githubusercontent.com/66891620/216165455-1e76878f-4ec5-4272-a806-71117474b5b5.png)

So umm... This isn't for BetterDiscord, it's for Xenoblade Chronicles.

**Comment by brwcat** [comment]
> So umm... This isn't for BetterDiscord, it's for Xenoblade Chronicles.

Ahh. It uses the exact same name.

**Comment by ghost** [comment]
> 

lmfaooo
