### ISSUE TITLE
Error for some reason

### ISSUE THREAD

**Issue by Nutelaspaceman** [PredatorCZ/XenoLib#8]
TypeError: Cannot read property 'NOOP_NULL' of undefined
    at eval (betterdiscord://plugins/XenoLib.plugin.js:1414:33)
    at buildPlugin (betterdiscord://plugins/XenoLib.plugin.js:1416:7)
    at eval (betterdiscord://plugins/XenoLib.plugin.js:2692:7)
    at eval (betterdiscord://plugins/XenoLib.plugin.js:2693:3)
    at Object.requireAddon (<anonymous>:4:43438)
    at Object.loadAddon (<anonymous>:4:9197)
    at Object.loadAddon (<anonymous>:4:41165)
    at AsyncFunction.<anonymous> (<anonymous>:4:7353)

**Comment by PredatorCZ** [comment]
You're posting to a wrong project, already discussed here: https://github.com/PredatorCZ/XenoLib/issues/3
