### ISSUE TITLE
XenoLib not working(

### ISSUE THREAD

**Issue by Timur4ikKasker** [PredatorCZ/XenoLib#9]
TypeError: Cannot read property 'NOOP_NULL' of undefined
    at eval (betterdiscord://plugins/1XenoLib.plugin.js:1414:33)
    at buildPlugin (betterdiscord://plugins/1XenoLib.plugin.js:1416:7)
    at eval (betterdiscord://plugins/1XenoLib.plugin.js:2692:7)
    at eval (betterdiscord://plugins/1XenoLib.plugin.js:2693:3)
    at Object.requireAddon (<anonymous>:4:43438)
    at Object.loadAddon (<anonymous>:4:9197)
    at Object.loadAddon (<anonymous>:4:41165)
    at Object.loadAllAddons (<anonymous>:4:11607)
    at Object.initialize (<anonymous>:4:6257)
    at Object.initialize (<anonymous>:4:40368)
    at Object.startup (<anonymous>:4:376262)

**Comment by DoomGGz** [comment]
where can I install XenoLib? I can't find it

**Comment by H3XDaemon** [comment]
Google took us to the wrong place
see #3

**Comment by DoomGGz** [comment]
dam ;-;

**Comment by DoomGGz** [comment]
but then where could I find it for betterdiscord @H3XDaemon

**Comment by o0SoloWolf0o** [comment]
TypeError: Cannot read property 'NOOP_NULL' of undefined
    at eval (betterdiscord://plugins/1XenoLib.plugin.js:1414:33)
    at buildPlugin (betterdiscord://plugins/1XenoLib.plugin.js:1416:7)
    at eval (betterdiscord://plugins/1XenoLib.plugin.js:2692:7)
    at eval (betterdiscord://plugins/1XenoLib.plugin.js:2693:3)
    at Object.requireAddon (<anonymous>:4:43438)
    at Object.loadAddon (<anonymous>:4:9197)
    at Object.loadAddon (<anonymous>:4:41165)
    at AsyncFunction.<anonymous> (<anonymous>:4:7353)
